(define (problem PlanLectura_Problema)
  (:domain PlanLectura)

  (:objects
    Libro1 Libro2 Libro3 Libro4 Libro5 Libro6 Libro7 Libro8 Libro9 Libro10 Libro11 Libro12 - libros_catalog
    Enero Febrero Marzo Abril Mayo Junio Julio Agosto Septiembre Octubre Noviembre Diciembre - mes
  )

  (:init
    (quiere_leer Libro1)
    (=(paginas_libro Libro1) 440)
    (quiere_leer Libro2)
    (=(paginas_libro Libro2) 289)
    (quiere_leer Libro3)
    (=(paginas_libro Libro3) 740)
    (quiere_leer Libro4)
    (=(paginas_libro Libro4) 114)
    (=(paginas_libro Libro5) 639)
    (=(paginas_libro Libro6) 108)
    (=(paginas_libro Libro7) 449)
    (=(paginas_libro Libro8) 575)
    (=(paginas_libro Libro9) 238)
    (=(paginas_libro Libro10) 329)
    (=(paginas_libro Libro11) 225)
    (=(paginas_libro Libro12) 243)
    (leido Libro7)
    (mes_lectura Libro7 Agosto)
    (leido Libro11)
    (mes_lectura Libro11 Junio)
    (leido Libro9)
    (mes_lectura Libro9 Marzo)
    (paralelos Libro6 Libro7)
    (paralelos Libro1 Libro2)
    (paralelos Libro3 Libro4)
    (mes_anterior Diciembre Enero)
    (mes_anterior Enero Febrero)
    (mes_anterior Febrero Marzo)
    (mes_anterior Marzo Abril)
    (mes_anterior Abril Mayo)
    (mes_anterior Mayo Junio)
    (mes_anterior Junio Julio)
    (mes_anterior Julio Agosto)
    (mes_anterior Agosto Septiembre)
    (mes_anterior Septiembre Octubre)
    (mes_anterior Octubre Noviembre)
    (mes_anterior Noviembre Diciembre)
    (=(pagines_mes Enero)0)
    (=(pagines_mes Febrero)0)
    (=(pagines_mes Marzo)0)
    (=(pagines_mes Abril)0)
    (=(pagines_mes Mayo)0)
    (=(pagines_mes Junio)0)
    (=(pagines_mes Julio)0)
    (=(pagines_mes Agosto)0)
    (=(pagines_mes Septiembre)0)
    (=(pagines_mes Octubre)0)
    (=(pagines_mes Noviembre)0)
    (=(pagines_mes Diciembre)0)
  )

  (:goal (forall (?l - libros_catalog) (imply (quiere_leer ?l) (leido ?l))))
)
