(define (problem PlanLectura_Problema)
  (:domain PlanLectura)

  (:objects
    Libro1 Libro2 Libro3 Libro4 Libro5 Libro6 Libro7 Libro8 Libro9 Libro10 - libros_catalog
    Enero Febrero Marzo Abril Mayo Junio Julio Agosto Septiembre Octubre Noviembre Diciembre - mes
  )

  (:init
    (quiere_leer Libro1)
    (=(paginas_libro Libro1) 243)
    (=(paginas_libro Libro2) 452)
    (=(paginas_libro Libro3) 166)
    (=(paginas_libro Libro4) 253)
    (=(paginas_libro Libro5) 526)
    (=(paginas_libro Libro6) 442)
    (=(paginas_libro Libro7) 315)
    (=(paginas_libro Libro8) 406)
    (=(paginas_libro Libro9) 797)
    (=(paginas_libro Libro10) 442)
    (predecesor Libro3 Libro4)
    (predecesor Libro8 Libro9)
    (predecesor Libro9 Libro10)
    (predecesor Libro1 Libro2)
    (paralelos Libro3 Libro4)
    (mes_anterior Diciembre Enero)
    (mes_anterior Enero Febrero)
    (mes_anterior Febrero Marzo)
    (mes_anterior Marzo Abril)
    (mes_anterior Abril Mayo)
    (mes_anterior Mayo Junio)
    (mes_anterior Junio Julio)
    (mes_anterior Julio Agosto)
    (mes_anterior Agosto Septiembre)
    (mes_anterior Septiembre Octubre)
    (mes_anterior Octubre Noviembre)
    (mes_anterior Noviembre Diciembre)
    (=(pagines_mes Enero)0)
    (=(pagines_mes Febrero)0)
    (=(pagines_mes Marzo)0)
    (=(pagines_mes Abril)0)
    (=(pagines_mes Mayo)0)
    (=(pagines_mes Junio)0)
    (=(pagines_mes Julio)0)
    (=(pagines_mes Agosto)0)
    (=(pagines_mes Septiembre)0)
    (=(pagines_mes Octubre)0)
    (=(pagines_mes Noviembre)0)
    (=(pagines_mes Diciembre)0)
  )

  (:goal (forall (?l - libros_catalog) (imply (quiere_leer ?l) (leido ?l))))
)
