(define (problem PlanLectura_Problema)
  (:domain PlanLectura)

  (:objects
    Libro11 Libro2 Libro1 Libro4 Libro3 Libro5 Libro6 Libro7 Libro8 Libro9 Libro10 Libro12 - libros_catalog
    Enero Febrero Marzo Abril Mayo Junio Julio Agosto Septiembre Octubre Noviembre Diciembre - mes
  )

  (:init
    (quiere_leer Libro11)
    (=(paginas_libro Libro11) 303)
    (quiere_leer Libro2)
    (=(paginas_libro Libro2) 171)
    (quiere_leer Libro1)
    (=(paginas_libro Libro1) 777)
    (quiere_leer Libro4)
    (=(paginas_libro Libro4) 303)
    (=(paginas_libro Libro3) 225)
    (=(paginas_libro Libro5) 430)
    (=(paginas_libro Libro6) 196)
    (=(paginas_libro Libro7) 385)
    (=(paginas_libro Libro8) 685)
    (=(paginas_libro Libro9) 430)
    (=(paginas_libro Libro10) 493)
    (=(paginas_libro Libro12) 117)
    (leido Libro5)
    (mes_lectura Libro5 Octubre)
    (leido Libro3)
    (mes_lectura Libro3 Enero)
    (leido Libro8)
    (mes_lectura Libro8 Noviembre)
    (paralelos Libro11 Libro12)
    (paralelos Libro4 Libro5)
    (mes_anterior Diciembre Enero)
    (mes_anterior Enero Febrero)
    (mes_anterior Febrero Marzo)
    (mes_anterior Marzo Abril)
    (mes_anterior Abril Mayo)
    (mes_anterior Mayo Junio)
    (mes_anterior Junio Julio)
    (mes_anterior Julio Agosto)
    (mes_anterior Agosto Septiembre)
    (mes_anterior Septiembre Octubre)
    (mes_anterior Octubre Noviembre)
    (mes_anterior Noviembre Diciembre)
    (=(pagines_mes Enero)225)
    (=(pagines_mes Febrero)0)
    (=(pagines_mes Marzo)0)
    (=(pagines_mes Abril)0)
    (=(pagines_mes Mayo)0)
    (=(pagines_mes Junio)0)
    (=(pagines_mes Julio)0)
    (=(pagines_mes Agosto)0)
    (=(pagines_mes Septiembre)0)
    (=(pagines_mes Octubre)430)
    (=(pagines_mes Noviembre)685)
    (=(pagines_mes Diciembre)0)
  )

  (:goal (forall (?l - libros_catalog) (imply (quiere_leer ?l) (leido ?l))))
)
